### ISSUE TITLE
find out why production impact for wood under biogenic/slash is negative

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#13]

**Comment by DEQmbrown2** [comment]
@DEQpcanepa , does this seem right to you?  Production of wood under the biogenic/slash option is negative.  See screenshot of wood production impacts as I have imported them below.

I guess this could make sense actually... when you produce wood you are sequestering carbon.  Even if you take out the slash penalty, it would still be sequestration.  However, the slash method doesn't say anything about "lost opportunities" for further sequestration (though our EpaFCS method does).  That's why epaFcs impacts are positive (that is, bad).  Just let me know if I got something wrong there...

martin

![image](https://user-images.githubusercontent.com/49459721/123350787-8d322980-d510-11eb-85cb-2b9e9faec14a.png)

**Comment by DEQmbrown2** [comment]
looks like there were negative production carbon impacts for several other materials too:
![image](https://user-images.githubusercontent.com/49459721/123351484-05e5b580-d512-11eb-93a3-40cc876d49dc.png)

**Comment by DEQmbrown2** [comment]
ps Peter -- in the unlikely case these questions lead to modifications of the gabi model, we can consider that part of the 1.0.1 release... so you don't necessarily need to prioritize it yet.  I'm thinking the 1.0.0 release should be based on exactly the things that CK reviewed?

**Comment by DEQpcanepa** [comment]
Hi Martin - yes the negative values reflect the fact that the trees which are turned into wood products sequester carbon from cradle to gate and are still negative even when accounting for slash emissions (our correction factor)  Without the slash emissions, the negative values would be higher (proportional to the estimated amount of slash we used in the model).  The values do not show-up negative under the EPA FCS because the amount of carbon lost due to harvest exceeds the sequestration values.

So in the screen capture below: A + B + C + D + E = Z

Where, A, B, C, D, are the proportional shares of different types of wood products contributing to the average "wood product" in WIC.

and where E is the Slash-related correction factor we calculated.

And where Z is the net GWP.

![Capture](https://user-images.githubusercontent.com/77121595/124979513-ff623e00-dfe7-11eb-9f9b-2db46a385d0e.PNG)

**Comment by DEQpcanepa** [comment]
At this point, I don't foresee any changes.  Generally, we should expect to see a "balancing" of the negative upfront emissions once end of life is included.  Though obviously depending on the disposition the amount of carbon that is emitted varies (e.g. incineration = direct release of stored carbon vs. landfilling = some release and some continued maintenance of stored carbon).

**Comment by DEQmbrown2** [comment]
Sounds good.  Thanks for the confirmation.  closing ticket.
