### ISSUE TITLE
confirm or deny certain odd Human Toxicity (cancer) impacts

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#57]
@DEQpcanepa , I've been using the new impact factors and they're great.  But odd results keep coming up in the Human Toxicity (cancer) category.  The impact factors are suggesting that production can be associated with negative toxicity (cancer) impacts... (I guess that would be a binding up of cancerous substances?) .   So the questions are:

* are these reasonable values?
* if not, should they be corrected?
* if yes, what process explains the negative results?  how can producing or burning stuff lessen cancer impacts?  (i can imagine several ways, but it's really speculating)

Here's a screenshot of where those appear in WIC results:
![image](https://user-images.githubusercontent.com/49459721/129646368-f39e5da3-539f-4bfe-9193-46237e6a031d.png)
.

I tracked this down to a certain subset of materials and dispositions where there are negative toxicity (cancer) impacts.  I've made a filtered spreadsheet of them which I will attach here.
[negative-impacts-in-production-cancer.xlsx](https://github.com/OR-Dept-Environmental-Quality/wic-base/files/6996181/negative-impacts-in-production-cancer.xlsx)

Looks like it's probably Scrap Metal production and Accepted Other Steel production where these things occur.  Also some kinds of incineration.  

Let me know what you think!  It guess it's possible cancer impacts are so speculative we should drop them from standard outputs?

**Comment by DEQmbrown2** [comment]
Got it, thanks for the digging.  For the time being I will just filter out this impact category from results.



________________________________

**Comment by DEQmbrown2** [comment]
Update-- thanks again for the digging.  I've also noticed a few odd results for human toxicity, non-cancer.  So what I'm going to do for the time being is not use either human toxicity category in the upcoming 1.1 release and app.

I'm going to push this issue back to the 1.2 release.  Hopefully by then we'll have some clarity.

**Comment by DEQpcanepa** [comment]
Just received a cursory response from Sphera, asking for me information.  Submitted that today, awaiting response.
[Email.pdf](https://github.com/OR-Dept-Environmental-Quality/wic-base/files/7124642/Email.pdf)

**Comment by DEQmbrown2** [comment]
Cool.  This is an issue I'd call "important but not urgent."

**Comment by DEQpcanepa** [comment]
I received more details back from Sphera regarding the steel datasets.  In short, there is no error that is leading to the negative human toxicity results.  While counter-intuitive, they are technically "correct."  

These results are based on how the steel inventory takes a credit for avoided cement production, due to slag (a co-product of steel production).  Specifically there is a single emission that is particularly toxic and associated with cement production.  So when cement production is avoided the absence of this emission leads to these negative results. I've attached the long email thread if you want more details.  Also, I've attached a second email on this same topic from 4 years ago, which I had with the Worldsteel association.  Obviously, there is inconsistency here between what the steel industry and concrete industry (producers and users of slag) are doing in their LCA models.  Both are taking credit for slag replacing cement....
[EmailResponse2.pdf](https://github.com/OR-Dept-Environmental-Quality/wic-base/files/7145799/EmailResponse2.pdf)
[WorldsteelEmailResponse.pdf](https://github.com/OR-Dept-Environmental-Quality/wic-base/files/7145800/WorldsteelEmailResponse.pdf)

The reason this has appeared in our latest results, was due to a change in underlying datasets that came from Christoph's technical review.  He proposed replacing the Worldsteel data with the AISI data, because the latter was being updated.  Both Worldsteel and AISI take this same credit, but the negative results in the AISI inventories reflect differences in the underlying models (e.g. amount of slag produced, type of cement substitution, energy grids, and more...).

So while the results are counter-intuitive, they can stand and we have some insights into why they are what they are.

**Comment by DEQmbrown2** [comment]
Thanks Peter, this is really substantial.  You've answered this, so I'll close the ticket (ka-ching!!).  But maybe I'll start a new one for later consideration about possible changes in release 1.2 or beyond.  I'm just trying to close up 1.1 now.

**Comment by DEQmbrown2** [comment]
Hello @DEQpcanepa , I've reopened this issue just to note we've gone another round on this.  I don't think there's anything you need to do here, other than review my work/take below and let me know if anything changes.

In the past week I've done one of my periodic updates to WIC.  I wanted to add human toxicity (cancer) impacts back in to the published version, but steel production was still showing a sizable impact credit for human toxicity (cancer).   This dominates the human toxicity results for Oregon's waste stream:
![image](https://github.com/OR-Dept-Environmental-Quality/wic-base/assets/49459721/5a6d81ee-7aff-4ea7-95b8-e523a0b2f868)

Your previous messages in this thread indicated this was technically correct but nonintuitive.  It had to do with steel production taking credit for avoided cement production.  Cement isn't currently part of WIC so there's nothing to really balance the other side of this credit.

One tweak I tried with this current update was to (as we discussed) replace the TRACI 2.1 human toxicity (cancer) category with the USEtox one, which had utilized more recent data.  This did not change the dramatic results in the pic above.

Anyway my impulse at this point is to (once again) eliminate human toxicity (cancer) from the published results.  Our figures might be technically correct in an academic way, but to the uninitiated it suggests that the way to eliminate cancerous emissions is to produce as much steel as possible -- which does not seem like a policy that protects the environment.

Let me know if you feel different! Martin
