### ISSUE TITLE
find out why food waste production has no transport impacts

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#9]

**Comment by DEQpcanepa** [comment]
Unfortunately food waste does have transportation impacts, but they are embedded within the "production" model.  This is because food is a mix of various food items (meat, grain, vegetable, dairy, eggs, etc...), each of which has a vastly different supply chain (e.g. tropical fruits come from tropical production regions vs. dairy comes from local sources).

Added a note to update text of "Impact-Modeling-for-the-WIC" to make clear that this transportation is included in production model, which differs from all other materials.

**Comment by DEQmbrown2** [comment]
Perfect, thank you.  Good idea for adding a note to the Impact Modeling doc.

Now I get to push that magic button: CLOSE ISSUE.  :)
